name: Lint

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: npm-cache-lint-node@16-${{ hashFiles('yarn.lock') }}

      - name: "Install dependencies"
        run: yarn install --frozen-lockfile --registry https://registry.npmjs.org --network-timeout 300000

      - name: ESLint
        run: yarn lint

      - name: Cargo fmt
        run: cargo fmt -- --check
